name: CI with Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: cache-c20766b

      - name: prime-cache-c20766b
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit for cache-c20766b"
          else
            echo "Cache miss for cache-c20766b"
          fi

      - name: Install dependencies
        run: npm init -y
